[package]
name = "tekutonu"
version = "0.1.0"
edition = "2021"

[dependencies]

bytemuck = "1.12"

cgmath = "0.18"

vulkano = "0.31"
vulkano-shaders = "0.31"
vulkano-win = "0.31"
winit = "0.27"

tracing = "0.1"
tracing-subscriber = "0.3"
